### ISSUE TITLE
Do not save searches

### ISSUE THREAD

**Issue by jasoncorum** [WGBH-MLA/bostonlocaltv#272]
problem: by default, Blacklight saves all searches. We're not using them, so that's just extra disk being taken up that we don't need. In this case, it has caused the production server to fail whenever doing a search.

Done when: searches are not saved.

**Comment by jasoncorum** [comment]
Found this in the Blacklight Google group: https://groups.google.com/forum/#!searchin/blacklight-development/searches$20table%7Csort:relevance/blacklight-development/1ZH5YYUCorU/WSk8xd8Ns5YJ

They're using a rake task to clear out the searches periodically.

**Comment by jasoncorum** [comment]
@afred: blacklight already provides a rake task to clear out the old searches: rake blacklight:delete_old_searches (it defaults to searches older than 7 days). 

if i remember correctly, i initially proposed a custom rake task (before finding the above), but you wanted something more akin to setting a configuration where we just never saved searches. to me, it seems like we should utilize what the community is using for the same issue.

if we were to go this route, we'd obviously need some way to schedule the task to run and it would be nice to keep that all within the application rather than relying on someone to create a cron task. what are your thoughts on using whenever? https://github.com/javan/whenever. it's pretty popular, probably due to being featured in railscasts years ago.

**Comment by afred** [comment]
Actually, I've been digging through code and now I'm curious as to what is actually causing our problem.

I was assuming that all searches are getting saved by default, but if that's the case, I'm not seeing where it happens in the code.

Blacklight makes a distinction between "search history" and "saved searches". The former is just a bit of Rails wrapper around the session. The latter is what actually writes records to the `searches` table. But afaict, it takes action by the user to do so.

So my assumption that every search is being saved may not be true. But if so, then something else is triggering the action to save the searches. And if that's the case, I'd be interested to see if there's an easy way to prevent it from happening. Asking people on Slack (acknowledging that it's Friday afternoon).

**Comment by afred** [comment]
Got a reply on slack to use `delete_old_searches`, so that's the recommended way. Still curious to find where they're getting saved automatically.

**Comment by jasoncorum** [comment]
@afred, so do you think using the rake task with whenever is the way to go? Or do you think another approach to call the rake task would be preferred?

**Comment by afred** [comment]
(answered on Hipchat) For now, let's avoid using `whenever` since all we need to do is put one cron file in place on the webserver. That can pretty easily be done with Capistrano already.

**Comment by jasoncorum** [comment]
Iceboxing because:

mimemagic‘s versions all yanked up to 0.3.7 (we were on 0.3.3)
mimemagic 0.3.7 requires nokogiri 1.11.2
Nokogiri 1.11.2 requires ruby 2.5
Current Rails (3.2.16) recommended Ruby version is 2.2
