### ISSUE TITLE
Add SSL to Site

### ISSUE THREAD

**Issue by singlesoliloquy** [WGBH-MLA/bostonlocaltv#300]
It wants all sites to have SSL.

## Done When

SSL and cron added.

**Comment by jasoncorum** [comment]
This site is on an EC2 instance running Amazon Linux AMI, an out-of-date OS that Amazon has placed in end-of-life support. Available documentation and support for adding SSL through Let's Encrypt in AWS is for machines running the AMI's predecessor, Amazon Linux 2. The effort needed to either figure out all the configuration needed for an AMI instance OR the effort to move BostonLocal to a machine running Amazon Linux 2 were deemed not worth the benefit.
