### ISSUE TITLE
Update Contact Info on BTVNDL

### ISSUE THREAD

**Issue by caseyedavis12** [WGBH-MLA/bostonlocaltv#302]
**User Story**
Boston TV News Digital Library contact us page should direct users to contact archive_requests@wgbh.org rather than Sadie's old email address.

**Done when**
Boston TV News Digital Library contact us page (http://bostonlocaltv.org/blog/contact/) is updated to the following:

## Contact
If you have general questions about the website and collections, or want to share information on the stories you find in the collections, please send an email to: **[archive_requests@wgbh.org](mailto:archive_requests@wgbh.org)**.

If you have questions about specific collections, including how to request a story be digitized, please send an email to:

CCTV Collection Cambridge Community Television: info [at] cctvcambridge [dot] org

Ten O’Clock News Collections WGBH Media Library and Archives: archive_requests [at] wgbh [dot] org

WCVB Collection Northeast Historic Films: kcarlson [at] oldfilm [dot] org

WHDH Collection Boston Public Library: ask [at] bpl [dot] org

**Comment by caseyedavis12** [comment]
@singlesoliloquy could this be prioritized for a quick fix sometime this week?

**Comment by singlesoliloquy** [comment]
@caseyedavis12 yes, it can.

**Comment by jasoncorum** [comment]
Per standup I manually made this edit on the production site and restarted and am submitting a PR for the change to Github.
