### ISSUE TITLE
Harvesters can get content from OAI endpoint.

### ISSUE THREAD

**Issue by afred** [WGBH-MLA/bostonlocaltv#88]
### User story

as a Harvester
i can use OAI harvesting protocol to retrieve all records
so that I can display them on my own site

Finished when:
Digital Commonwealth confirms that they have all of our records.

**Comment by mccalluc** [comment]
@sroosa : Where does this stand? Did OAI-PMH work once? Will it ever need to work again?

**Comment by sroosa** [comment]
@mccalluc : I'm not sure if this ever worked. I know that it was worked on, but Digital Commonwealth never harvested from it, so I'm not sure it was ever completed or tested. It does need to work. We do want the assets on this website harvested by Digital Commonwealth.

**Comment by sroosa** [comment]
Working now
